TARGET = 'Loan Status'

NUMERICAL_FEATURES = [
    "Loan Amount",
    "Funded Amount",
    "Funded Amount Investor",
    "Term",
    "Interest Rate",
    "Home Ownership",
    "Debit to Income",
    "Delinquency - two years",
    "Inquires - six months",
    "Open Account",
    "Public Record",
    "Revolving Balance",
    "Revolving Utilities",
    "Total Accounts",
    "Total Received Interest",
    "Total Received Late Fee",
    "Recoveries",
    "Collection Recovery Fee",
    "Collection 12 months Medical",
    "Last week Pay",
    "Accounts Delinquent",
    "Total Collection Amount",
    "Total Current Balance",
    "Total Revolving Credit Limit",
]

CATEGORICAL_FEATURES = [
    "Batch Enrolled",
    "Grade",
    "Sub Grade",
    "Employment Duration",
    "Verification Status",
    "Payment Plan",
    "Loan Title",
    "Initial List Status",
    "Application Type",
]
